import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import ProfileCard from "@/components/ProfileCard";

import "./globals.css";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ProfileCard />
          <ChakraProvider>{children}</ChakraProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
